In [ ]:
import pandas as pd
from config import *

In [3]:
CLIENT_ID = client_id
CLIENT_SECRET = client_secret

# URLs de los endpoints
endpoint_1 = f'https://apitransporte.buenosaires.gob.ar/ecobici/gbfs/stationInformation?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}'
endpoint_2 = f"https://apitransporte.buenosaires.gob.ar/ecobici/gbfs/stationStatus?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}"

In [7]:
def get_and_clean_df(endpoint):
    json = pd.read_json(endpoint)
    df = pd.DataFrame(json['data'][0])
    
    if endpoint == endpoint_1:
        columnas_a_eliminar = ['physical_configuration', 'altitude', 'is_charging_station',
                       'obcn', '_ride_code_support', 'rental_uris', 'cross_street', 'post_code', 'rental_methods',	'groups','short_name',	'nearby_distance']

        # Eliminar las columnas especificadas
        df = df.drop(columns=columnas_a_eliminar)
        df['station_id'] = df['station_id'].astype('int64')
    elif endpoint == endpoint_2:
        columnas_a_eliminar = ['num_bikes_available_types', 'is_charging_station', 'traffic']

         # Eliminar las columnas especificadas
        df = df.drop(columns=columnas_a_eliminar)
        df['last_reported'] = pd.to_datetime(df['last_reported'], unit='s') 
        df['station_id'] = df['station_id'].astype('int64')   
    return df

In [8]:

df_1 = get_and_clean_df(endpoint_1)         

df_1

,station_id,name,lat,lon,address,capacity
0,2,002 - Retiro I,-34.592424,-58.374710,AV. Dr. José María Ramos Mejía 1300,40
1,3,003 - ADUANA,-34.612207,-58.369129,Av. Paseo Colón 380,28
2,4,004 - Plaza Roma,-34.603008,-58.368856,Av. Corrientes 100,20
3,5,005 - Plaza Italia,-34.580550,-58.420954,Av. Sarmiento 2601,42
4,6,006 - Parque Lezama,-34.628526,-58.369758,"Avenida Martin Garcia, 295",20
...,...,...,...,...,...,...
394,587,351 - PAYSANDU,-34.616370,-58.449870,Paysandú 573,20
395,588,400 - HIDALGO,-34.606153,-58.441754,Hidalgo 1210,16
396,589,016 - MUSEO DEL AGUA,-34.600982,-58.395457,Viamonte 1994,16
397,590,392 - CHARCAS,-34.586866,-58.421426,Paraguay 4226,16
398,591,398 - MERCEDES,-34.604763,-58.509574,Av. Francisco Beiró 4150,16

In [12]:

df_2 = get_and_clean_df(endpoint_2)         

df_2

,station_id,num_bikes_available,num_bikes_disabled,num_docks_available,num_docks_disabled,last_reported,status,is_installed,is_renting,is_returning
0,2,10,0,30,0,2025-04-08 21:17:42,IN_SERVICE,1,1,1
1,3,2,5,21,0,2025-04-08 21:18:39,IN_SERVICE,1,1,1
2,4,3,0,17,0,2025-04-08 21:18:51,IN_SERVICE,1,1,1
3,5,1,2,39,0,2025-04-08 21:17:04,IN_SERVICE,1,1,1
4,6,8,3,9,1,2025-04-08 21:17:32,IN_SERVICE,1,1,1
...,...,...,...,...,...,...,...,...,...,...
394,587,5,0,15,1,2025-04-08 21:17:23,IN_SERVICE,1,1,1
395,588,7,0,9,0,2025-04-08 21:15:45,IN_SERVICE,1,1,1
396,589,0,0,16,0,2025-04-08 21:16:47,IN_SERVICE,1,1,1
397,590,1,0,15,0,2025-04-08 21:16:59,IN_SERVICE,1,1,1
398,591,1,0,15,0,2025-04-08 21:18:27,IN_SERVICE,1,1,1